name: pet_owner_app
description: A Flutter app to manage pet owners and their animals using SQLite.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gemini: ^3.0.0
  font_awesome_flutter: ^10.4.0
  sqflite: ^2.2.8
  path: ^1.8.3
  bcrypt: ^1.1.3
  path_provider: ^2.0.14
  image_picker: ^0.8.7+5
  http: ^1.5.0
  mailer: ^6.0.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  fl_chart: ^0.68.0
  geolocator: ^12.0.0
  url_launcher: ^6.2.1
  add_2_calendar: ^3.0.0
  table_calendar: ^3.1.0
  intl: ^0.19.0
  collection: ^1.18.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cached_network_image: ^3.3.0  # Pour cacher les images
  provider: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo2.png
