name: pet_owner_app
description: A Flutter app to manage pet owners and their animals using SQLite.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  sqflite: ^2.2.8
  path: ^1.8.3
  path_provider: ^2.0.14
  image_picker: ^0.8.7+5
  http: ^1.1.0           # Pour les API calls
  cached_network_image: ^3.3.0  # Pour cacher les images
  provider: ^6.1.1       # State management (optionnel)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo2.png
